### ISSUE TITLE
Support for NuShell

### ISSUE THREAD

**Issue by diversable** [vitorgalvao/run-command-workflow#1]
### Feature details

First off, thank you for setting up this workflow! Great work!

What would make this workflow even better, though, is if it also supported NuShell (https://www.nushell.sh/) in addition to Zsh & Bash. 

I'm still new to writing Alfred Workflows, but if there's some way I can contribute to adding NuShell support to this Workflow, please let me know.

Cheers!

**Comment by vitorgalvao** [comment]
Thank you for the request, but that is specifically something I won’t add. Previous versions of the workflow supported more shells and those are a pain to manage, each with their own idiosyncrasies. And because they are not standard, a bunch of trickery is necessary to completely isolate them. Plus, I’m not familiar with NuShell (I heard of it, but never used it) which would make debugging it particularly troublesome, for something used by a tiny percentage of users. If I were to support more shells (not something I want to pursue) something more popular like Fish would take precedence. It is a conscious decision to only support Bash and Zsh.
